on: push

jobs:
  missing-git-executable:
    runs-on: dennis-windows-arm64
    steps:
      # This will use the GitHub API since Git isn't installed on the runner
      - name: clone git-for-windows-automation
        uses: actions/checkout@v4
      # This will fail because Git isn't installed on the runner
      - uses: dennisameling/setup-git-for-windows-sdk@e95ed5e0269958503b1ffbd56a5859c8f26d8a2b
        continue-on-error: true
        with:
          flavor: build-installers
          architecture: aarch64
      - name: install GfW
        shell: powershell
        run: |
          & ./azure-self-hosted-runners/post-deployment-script.ps1
          Add-Content $env:GITHUB_PATH "C:\Program Files\Git\bin"
          $currentPath = [System.Environment]::GetEnvironmentVariable("PATH", "Machine")
          $newPath = 'C:\Program Files\Git\bin;' + $currentPath
          [Environment]::SetEnvironmentVariable("PATH", $newPath, "Machine")
      - name: try installing the SDK again
        uses: dennisameling/setup-git-for-windows-sdk@e95ed5e0269958503b1ffbd56a5859c8f26d8a2b
        with:
          flavor: build-installers
          architecture: aarch64
  should-work-on-hosted-runner:
    runs-on: windows-latest
    steps:
      # This should work because the hosted runner has Git installed. Let's see what it logs as its PATH.
      - uses: dennisameling/setup-git-for-windows-sdk@e95ed5e0269958503b1ffbd56a5859c8f26d8a2b
        continue-on-error: true
        with:
          flavor: build-installers
          architecture: aarch64
